import { Turf } from './types';

export const MOCK_TURFS: Turf[] = [
  {
    id: 'shine-arena-mysuru',
    name: "Shine Arena (Football and Cricket Turf)",
    location: '23 2nd Stage, Devanur, Rajiv Nagar Rd, N.R Mohalla, Mysuru, Karnataka 570007',
    area: 'N.R Mohalla',
    sportTypes: ['Football', 'Cricket'],
    courtTypes: ['Half Court', 'Full Court'],
    pricePerHour: 1000,
    courtPricing: {
      "Half Court": 1000,
      "Full Court": 1400
    },
    rating: 5.0,
    reviewCount: 1,
    mainImage: 'https://picsum.photos/seed/shine1/1200/800',
    galleryImages: ['https://picsum.photos/seed/shine2/1200/800'],
    description: "Premium sporting facility located in N.R Mohalla, Shine Arena offers elite surfaces for both football and cricket enthusiasts. Perfect for community matches and professional practice.",
    amenities: ['Floodlights', 'Parking', 'Water'],
    coachingServices: [],
    openingHours: 'Open • Closes 11 PM',
    contactNumber: '',
    whatsappNumber: '917411322492',
    mapUrl: 'https://maps.google.com/?q=Shine+Arena+Rajiv+Nagar+Mysuru',
    isPopular: true
  },
  {
    id: 'kmfc-krazy-mysore-football-club',
    name: 'KMFC - Krazy Mysore Football Club',
    location: 'Krazy Bowl Compound, Mysore Bangalore Highway, opposite K.R Mill, Hale Kesare, Karnataka 570003',
    area: 'Hale Kesare',
    sportTypes: ['Football'],
    courtTypes: ['Half Court', 'Full Court'],
    pricePerHour: 1200,
    courtPricing: {
      "Half Court": 1200,
      "Full Court": 1800
    },
    rating: 4.9,
    reviewCount: 71,
    mainImage: 'https://picsum.photos/seed/kmfc1/1200/800',
    galleryImages: ['https://picsum.photos/seed/kmfc2/1200/800'],
    description: "Located on the Bangalore highway, KMFC is one of Mysuru's most popular football destinations. Professional-grade turf and high-intensity match environments.",
    amenities: ['Pro Floodlights', 'Cafe', 'Changing Rooms'],
    coachingServices: ['Youth Academy'],
    openingHours: 'Open • Closes 11 PM',
    contactNumber: '08553552553',
    whatsappNumber: '918553552553',
    mapUrl: 'https://maps.google.com/?q=KMFC+Mysore+Bangalore+Highway',
    isPopular: true
  },
  {
    id: 'sunrise-sports-arena',
    name: 'Sunrise Sports Arena',
    location: 'Shivarathreeshwara Nagar, Bannimantap, Mysuru, Karnataka 570015',
    area: 'Bannimantap',
    sportTypes: ['Football'],
    courtTypes: ['Half Court', 'Full Court'],
    pricePerHour: 1100,
    courtPricing: {
      "Half Court": 1100,
      "Full Court": 1600
    },
    rating: 4.6,
    reviewCount: 151,
    mainImage: 'https://picsum.photos/seed/sunrise1/1200/800',
    galleryImages: [],
    description: "Central sports hub in Bannimantap offering quality surfaces for football. A community favorite for weekend evening matches.",
    amenities: ['Lighting', 'Drinking Water'],
    coachingServices: [],
    openingHours: 'Open • Closes 11 PM',
    contactNumber: '08660920743',
    whatsappNumber: '918660920743',
    mapUrl: 'https://maps.google.com/?q=Sunrise+Sports+Arena+Bannimantap',
    isPopular: false
  },
  {
    id: 'perfect-pass-mysore',
    name: 'Perfect Pass Mysore',
    location: '40/1, Bannur Rd, Shakthinagar, Mysuru, Karnataka 570029',
    area: 'Shakthinagar',
    sportTypes: ['Football'],
    courtTypes: ['Football Academy'],
    pricePerHour: 1000,
    courtPricing: {
      "Session": 1000
    },
    rating: 4.6,
    reviewCount: 136,
    mainImage: 'https://picsum.photos/seed/pp1/1200/800',
    galleryImages: [],
    description: "Focused on football excellence, Perfect Pass in Shakthinagar provides a professional training ground and match surface for serious players.",
    amenities: ['Academy Training', 'Floodlights'],
    coachingServices: ['Football Academy'],
    openingHours: 'Open • Closes 11 PM',
    contactNumber: '08296462747',
    whatsappNumber: '918296462747',
    mapUrl: 'https://maps.google.com/?q=Perfect+Pass+Bannur+Road+Mysuru',
    isPopular: false
  },
  {
    id: 'kubers-turf-mysuru',
    name: "Kuber’s Turf",
    location: '9, Sahukar Chenniah Road, Kuvempunagara North, TK Layout, Bhogadi, Mysuru, Karnataka 570009',
    area: 'Bhogadi',
    sportTypes: ['Football', 'Cricket'],
    courtTypes: ['Half Court', 'Full Court'],
    pricePerHour: 900,
    courtPricing: {
      "Half Court": 900,
      "Full Court": 1300
    },
    rating: 4.4,
    reviewCount: 30,
    mainImage: 'https://picsum.photos/seed/kuber1/1200/800',
    galleryImages: [],
    description: "Vibrant multi-sport turf in the heart of Bhogadi/TK Layout area. High visibility and excellent connectivity.",
    amenities: ['Parking', 'Lighting'],
    coachingServices: [],
    openingHours: 'Open • Closes 10:30 PM',
    contactNumber: '07795797627',
    whatsappNumber: '917795797627',
    mapUrl: 'https://maps.google.com/?q=Kuber+Turf+Bhogadi+Mysuru',
    isPopular: true
  },
  {
    id: 'perfect-x-arena',
    name: 'Perfect X Arena',
    location: 'Sy 85/2, near sea food joint, Bogadi 2nd Stage, Bogadi 2nd Stage North, Mysuru, Karnataka 570026',
    area: 'Bogadi',
    sportTypes: ['Cricket', 'Football'],
    courtTypes: ['Box Cricket', '7A Side Football', '5A Side Football'],
    pricePerHour: 1400,
    courtPricing: {
      "Box Cricket": 800,
      "5A Side": 1400,
      "7A Side": 2400
    },
    rating: 4.9,
    reviewCount: 25,
    mainImage: 'https://picsum.photos/seed/px1/1200/800',
    galleryImages: [],
    description: "Elite sporting arena in Bogadi Stage 2. Known for its massive 7-a-side pitch and specialized box cricket setups.",
    amenities: ['International Standard Turf', 'Premium LED', 'Parking'],
    coachingServices: [],
    openingHours: 'Open 24 hours',
    contactNumber: '09686299909',
    whatsappNumber: '919686299909',
    mapUrl: 'https://maps.google.com/?q=Perfect+X+Arena+Bogadi+Mysuru',
    isPopular: true
  },
  {
    id: 'patel-turfbox-mysuru',
    name: 'PatelTurfBox',
    location: 'Beml layout Main Road, near Kingdom Restaurant, Sriramapura, Sriramapura, Karnataka 570033',
    area: 'Sriramapura',
    sportTypes: ['Football', 'Cricket'],
    courtTypes: ['Half Court', 'Full Court'],
    pricePerHour: 1000,
    courtPricing: {
      "Half Court": 1000,
      "Full Court": 1500
    },
    rating: 4.9,
    reviewCount: 152,
    mainImage: 'https://picsum.photos/seed/patel1/1200/800',
    galleryImages: [],
    description: "Top-tier box cricket and football facility in Sriramapura. Features high-density shock-absorbent turf.",
    amenities: ['Floodlights', 'Dressing Room'],
    coachingServices: [],
    openingHours: 'Open • Closes 10 PM',
    contactNumber: '08217587207',
    whatsappNumber: '918217587207',
    mapUrl: 'https://maps.google.com/?q=Patel+Turf+Box+Sriramapura',
    isPopular: false
  },
  {
    id: 'matchbox-hebbal',
    name: 'Matchbox Hebbal',
    location: 'Plot Number 31, Survey Number 115, Hebbal Village, kasaba Hobli, Mysuru, Karnataka 570017',
    area: 'Hebbal',
    sportTypes: ['Pickleball', 'Football'],
    courtTypes: ['Pickleball Court', 'Football Court'],
    pricePerHour: 1200,
    courtPricing: {
      "Pickleball Court": 600,
      "Football": 1200
    },
    rating: 4.8,
    reviewCount: 72,
    mainImage: 'https://picsum.photos/seed/match1/1200/800',
    galleryImages: [],
    description: "Modern sports park in Hebbal featuring Mysuru's fastest-growing Pickleball scene along with premium football facilities.",
    amenities: ['Pickleball Gear', 'Floodlights', 'Cafe'],
    coachingServices: ['Pickleball Lessons'],
    openingHours: 'Open 24 hours',
    contactNumber: '09620192323',
    whatsappNumber: '919620192323',
    mapUrl: 'https://maps.google.com/?q=Matchbox+Hebbal+Mysuru',
    isPopular: true
  }
];
