import { Turf } from './types';

export const MOCK_TURFS: Turf[] = [
  {
    id: '1',
    name: 'Champions Arena',
    location: 'Vijayanagar 2nd Stage, Mysuru',
    area: 'Vijayanagar',
    sportTypes: ['Football', 'Cricket'],
    pricePerHour: 1200,
    rating: 4.8,
    reviewCount: 156,
    images: ['https://picsum.photos/seed/turf1/800/600', 'https://picsum.photos/seed/turf4/800/600'],
    description: 'Premier sports facility with international standard turf quality. Perfect for 5-a-side football and box cricket tournaments.',
    amenities: ['Floodlights', 'Changing Rooms', 'Drinking Water', 'Parking', 'Scoreboard'],
    openingHours: '06:00 AM - 12:00 AM',
    contactNumber: '+91 9876543210',
    whatsappNumber: '919876543210',
    mapUrl: 'https://maps.google.com/?q=Vijayanagar+Mysuru',
    isPopular: true
  },
  {
    id: '2',
    name: 'The Dugout',
    location: 'Hebbal, Industrial Area, Mysuru',
    area: 'Hebbal',
    sportTypes: ['Football'],
    pricePerHour: 1000,
    rating: 4.5,
    reviewCount: 89,
    images: ['https://picsum.photos/seed/turf2/800/600', 'https://picsum.photos/seed/turf3/800/600'],
    description: 'The ultimate football destination in Hebbal. High-quality synthetic grass and excellent lighting for night matches.',
    amenities: ['Floodlights', 'Seating Area', 'Parking'],
    openingHours: '24 Hours',
    contactNumber: '+91 9876543211',
    whatsappNumber: '919876543211',
    mapUrl: 'https://maps.google.com/?q=Hebbal+Mysuru',
    isPopular: true
  },
  {
    id: '3',
    name: 'Strike Zone Cricket Academy',
    location: 'Saraswathipuram, Mysuru',
    area: 'Saraswathipuram',
    sportTypes: ['Cricket'],
    pricePerHour: 1500,
    rating: 4.9,
    reviewCount: 210,
    images: ['https://picsum.photos/seed/turf3/800/600'],
    description: 'Premium indoor and outdoor cricket facility with multiple lanes and bowling machines available on request.',
    amenities: ['Floodlights', 'Bowling Machine', 'Locker Room', 'Coach Support'],
    openingHours: '05:00 AM - 10:00 PM',
    contactNumber: '+91 9876543212',
    whatsappNumber: '919876543212',
    mapUrl: 'https://maps.google.com/?q=Saraswathipuram+Mysuru',
    isPopular: false
  },
  {
    id: '4',
    name: 'Elite Turf Mysuru',
    location: 'Jayalakshmipuram, Mysuru',
    area: 'Jayalakshmipuram',
    sportTypes: ['Football', 'Cricket'],
    pricePerHour: 1300,
    rating: 4.7,
    reviewCount: 45,
    images: ['https://picsum.photos/seed/turf4/800/600'],
    description: 'Newly launched premium turf with top-tier amenities and a vibrant atmosphere for competitive games.',
    amenities: ['Floodlights', 'Changing Rooms', 'Cafeteria', 'Parking'],
    openingHours: '06:00 AM - 11:30 PM',
    contactNumber: '+91 9876543213',
    whatsappNumber: '919876543213',
    mapUrl: 'https://maps.google.com/?q=Jayalakshmipuram+Mysuru',
    isPopular: false
  }
];