import { Turf } from './types';

export const MOCK_TURFS: Turf[] = [
  {
    id: 'kuber',
    name: "Kuber's Turf",
    location: 'Near Kuvempunagar, Mysuru',
    area: 'Kuvempunagar',
    sportTypes: ['Football', 'Cricket'],
    courtTypes: ['Full Court'],
    pricePerHour: 1200,
    rating: 4.4,
    reviewCount: 128,
    images: ['https://picsum.photos/seed/kuber1/800/600', 'https://picsum.photos/seed/kuber2/800/600'],
    description: "Kuber's Turf is a premium sports destination in Kuvempunagar, offering high-quality synthetic grass suitable for both intense football matches and competitive cricket sessions.",
    amenities: ['Floodlights', 'Changing Rooms', 'Drinking Water', 'Parking'],
    openingHours: '06:00 AM - 10:30 PM',
    contactNumber: '+91 9900000001',
    whatsappNumber: '919900000001',
    mapUrl: 'https://maps.google.com/?q=Kuvempunagar+Mysuru',
    isPopular: true
  },
  {
    id: 'perfect-x',
    name: 'Perfect X Arena',
    location: 'Bogadi 2nd Stage, Mysuru',
    area: 'Bogadi',
    sportTypes: ['Football', 'Cricket'],
    courtTypes: ['Half Court', 'Full Court'],
    pricePerHour: 1500,
    rating: 5.0,
    reviewCount: 245,
    images: ['https://picsum.photos/seed/perfect1/800/600', 'https://picsum.photos/seed/perfect2/800/600'],
    description: 'The ultimate sports arena in Bogadi. Featuring both Half Court and Full Court options for box cricket and football. Open 24/7 for the true sports enthusiasts.',
    amenities: ['Floodlights', 'Seating Area', 'Parking', 'Refreshments', 'Scoreboard'],
    openingHours: '24 Hours',
    contactNumber: '+91 9900000002',
    whatsappNumber: '919900000002',
    mapUrl: 'https://maps.google.com/?q=Bogadi+Mysuru',
    isPopular: true
  },
  {
    id: 'patel',
    name: 'Patel TurfBox',
    location: 'Srirampura, Mysuru',
    area: 'Srirampura',
    sportTypes: ['Cricket', 'Football'],
    courtTypes: ['Full Court'],
    pricePerHour: 1100,
    rating: 4.9,
    reviewCount: 167,
    images: ['https://picsum.photos/seed/patel1/800/600', 'https://picsum.photos/seed/patel2/800/600'],
    description: 'Located in Srirampura, Patel TurfBox provides a professional environment for cricket and football lovers. Known for its well-maintained turf and excellent lighting.',
    amenities: ['Floodlights', 'Locker Room', 'Parking'],
    openingHours: '06:00 AM - 10:00 PM',
    contactNumber: '+91 9900000003',
    whatsappNumber: '919900000003',
    mapUrl: 'https://maps.google.com/?q=Srirampura+Mysuru',
    isPopular: false
  },
  {
    id: 'matchbox',
    name: 'Matchbox',
    location: 'Vijayanagar 4th Stage, Mysuru',
    area: 'Vijayanagar',
    sportTypes: ['Football'],
    courtTypes: ['Full Court'],
    pricePerHour: 1300,
    rating: 4.5,
    reviewCount: 312,
    images: ['https://picsum.photos/seed/match1/800/600', 'https://picsum.photos/seed/match2/800/600'],
    description: 'Matchbox is the heartbeat of Vijayanagar football. A full-court facility designed for high-octane 5-a-side or 7-a-side matches, available around the clock.',
    amenities: ['Floodlights', 'Spectator Stand', 'Parking', 'Cafeteria'],
    openingHours: '24 Hours',
    contactNumber: '+91 9900000004',
    whatsappNumber: '919900000004',
    mapUrl: 'https://maps.google.com/?q=Vijayanagar+Mysuru',
    isPopular: true
  }
];
